### ISSUE TITLE
ipmctl  show -memoryresources ,invalid PCD data

### ISSUE THREAD

**Issue by chiachuanwu** [intel/ipmctl#123]
tag v02.00.00.3658 "ipmctl  show -memoryresources" command show invalid PCD data.
the full log as below:
_One or more DIMMs have invalid PCD data. A platform reboot is recommended to restore valid PCD data, then try again._

Hardware Condition:
Latest Intel Xeon processor
Second generation Intel Optane DIMM.

But Master branch commit ID"a47b0b85fdbcee5ff94385fc2408136baf58f8a7" ipmctl show -memoryresources working fine on the same system.

**Comment by kellycouch** [comment]
Thanks for reporting, we will investigate this.

**Comment by kellycouch** [comment]
Is it possible for you to provide a recording file to expedite debug?

```
ipmctl start -session -mode record
ipmctl show -memoryresources
ipmctl dump -destination show-mr.pbr -session
ipmctl stop -session
```
Then attach the recorded file 'show-mr.pbr'.

**Comment by chiachuanwu** [comment]
[show-mr.zip](https://github.com/intel/ipmctl/files/3914100/show-mr.zip)
here you go.

**Comment by chiachuanwu** [comment]
```
root@clr-f1430a4599d640e3b0b4de485393ee0f~ # ipmctl version
Intel(R) Optane(TM) DC Persistent Memory Command Line Interface Version 01.00.00.9999
```
```
 uname -a
Linux clr-f1430a4599d640e3b0b4de485393ee0f 5.3.11-868.native #1 SMP Wed Nov 13 15:46:39 PST 2019 x86_64 GNU/Linux
```

**Comment by chiachuanwu** [comment]
Please let me know any other information you need.

**Comment by kellycouch** [comment]
The error message was misleading/incorrect. This command failed because of inability to parse ACPI PMTT table. May I ask what platform you are on? Does your BIOS publish PMTT?

**Comment by chiachuanwu** [comment]
[show-mr_good.zip](https://github.com/intel/ipmctl/files/3920137/show-mr_good.zip)
ipmctl show -memoryresources command working fine on the other same platform, but with newer version of BIOS, i had attached recorded file for comparison.

**Comment by mp15** [comment]
I can still replicate this bug using the current testing version of ipmctl (testing b259158292ff8ca43fab0011254256b34da7359f) with the fixes it contains. Would it be helpful for me to provide a debug dump to confirm whether or not this is the same issue?

**Comment by mp15** [comment]
Retested and appears fixed with v02.00.00.3709 (7543fc7c1e746addb2fb661951e06eaae1841cef)

**Comment by Muthu2112** [comment]
Observing similar issue in IPMCTL 01.00.00.3497. So should i use V02.00.00 series to test this ?

**Comment by zjs1224522500** [comment]
Still exists in v02.00.00.3709 with kernel version Linux 5.15.0-69-generic.

**Comment by nolanhergert** [comment]
Sorry for the delay. Can you try a newer version of ipmctl? There were some additional fixes checked into newer versions, specifically 3882 or newer.

**Comment by zjs1224522500** [comment]
> ipmctl

Sorry for late reply. After upgrading the version to 02.00.00.3885, this issue is fixed.

Thanks~
